#!/usr/bin/env python3
"""Write docs/VARIABLES_REFERENCE.md: every setting in every roles/*/defaults/main.yml, with its
default and the comment written above it. The role files stay the single source of truth.

    python scripts/gen_variable_reference.py            # rewrite the reference
    python scripts/gen_variable_reference.py --check    # exit 1 when the file is out of date (CI)

Standard library only. It reads the files as text (a comment belongs to the setting right below it).
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "VARIABLES_REFERENCE.md")
KEY = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):(?:\s+(.*))?$")
MAX_VALUE = 90
MAX_DOC = 320


def strip_inline_comment(text):
    """Cut a trailing ' # comment' that is not inside quotes; return (value, comment)."""
    quote = ""
    for i, ch in enumerate(text):
        if quote:
            if ch == quote:
                quote = ""
        elif ch in "'\"":
            quote = ch
        elif ch == "#" and (i == 0 or text[i - 1] in " \t"):
            return text[:i].rstrip(), text[i + 1:].strip()
    return text.rstrip(), ""


def parse_defaults(path):
    """-> (header, [ {name, value, doc} ]) for one defaults file."""
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    header, settings = [], []
    block, section, seen_blank = [], [], False   # block: comment lines right above; section: blank-separated
    i, first_var = 0, True
    while i < len(lines):
        line = lines[i]
        if line.strip() == "---":
            i += 1
            continue
        if not line.strip():
            if block:
                if not settings and not header:
                    header = block
                else:
                    section = block
            block, seen_blank = [], True
            i += 1
            continue
        if line.startswith("#"):
            block.append(re.sub(r"^#\s?", "", line).rstrip())
            i += 1
            continue
        m = KEY.match(line)
        if not m:
            i += 1
            continue
        name, rest = m.group(1), m.group(2) or ""
        first_var = False
        value, inline = strip_inline_comment(rest)
        j = i + 1
        extra = []
        while j < len(lines) and (lines[j].startswith((" ", "\t", "- ")) or not lines[j].strip()):
            if lines[j].strip() and not lines[j].lstrip().startswith("#"):
                extra.append(lines[j].strip())
            elif not lines[j].strip():
                break
            j += 1
        if extra:
            value = (value + " " + " ".join(extra)).strip()
        doc = list(block)
        if not doc and section:
            doc = section
        if inline:
            doc = doc + [inline]
        settings.append({"name": name, "value": value, "doc": doc})
        block, section = [], []
        i = j
    if not settings and block and not header:
        header = block
    return header, settings


def cell(text):
    return text.replace("|", "\\|").replace("\n", " ").strip()


def shorten(value):
    value = re.sub(r"\s+", " ", value).strip()
    if value.startswith((">", "|")) or value.startswith("{{"):
        return "(worked out by the role; see its file)"
    if value in ("", '""', "''"):
        return "(empty)"
    if len(value) > MAX_VALUE:
        value = value[:MAX_VALUE - 1].rstrip() + "…"
    return "`" + value.replace("`", "'") + "`"


def roles_with_settings():
    found = []
    for path in sorted(glob.glob(os.path.join(ROOT, "roles", "*", "defaults", "main.yml"))):
        if parse_defaults(path)[1]:
            found.append(os.path.basename(os.path.dirname(os.path.dirname(path))))
    return found


def render():
    out = [
        "# Every setting and its default",
        "",
        "<!-- GENERATED by scripts/gen_variable_reference.py from roles/*/defaults/main.yml. Do not edit by hand:",
        "     change the comment in the role's defaults file and run the script. -->",
        "",
        "This page lists **every setting a role reads**, with the value it has when you set nothing, and",
        "what the role's own comment says. It is generated from `roles/<role>/defaults/main.yml`, so it is",
        "never out of date. Where to put a setting, and which place wins when it is in two, is in",
        "[VARIABLES.md](VARIABLES.md). Values are shortened to one line here: the role file has the full one.",
        "",
        "A setting that is a list (`[a, b]`) **replaces** the default list when you set it; it does not add",
        "to it. Repeat the entries you want to keep.",
        "",
        "**Contents:** " + ", ".join("[%s](#%s)" % (r, r) for r in roles_with_settings()),
        "",
    ]
    for path in sorted(glob.glob(os.path.join(ROOT, "roles", "*", "defaults", "main.yml"))):
        role = os.path.basename(os.path.dirname(os.path.dirname(path)))
        header, settings = parse_defaults(path)
        if not settings:
            continue
        out.append("## " + role)
        out.append("")
        out.append("File: `roles/%s/defaults/main.yml`" % role)
        out.append("")
        if header:
            out.append("> " + cell(" ".join(h for h in header if h)))
            out.append("")
        out.append("| Setting | Default | What it does |")
        out.append("|---|---|---|")
        for s in settings:
            doc = re.sub(r"\s+", " ", " ".join(d for d in s["doc"] if d.strip())).strip()
            if len(doc) > MAX_DOC:
                doc = doc[:MAX_DOC - 1].rstrip() + "… (all of it: the role file)"
            out.append("| `%s` | %s | %s |" % (s["name"], cell(shorten(s["value"])), cell(doc)))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv):
    if any(a in ("-h", "--help") for a in argv):
        print(__doc__)
        return 0
    unknown = [a for a in argv if a != "--check"]
    if unknown:   # never rewrite the file because of a typo
        sys.stderr.write("unknown argument(s): %s (only --check)\n" % " ".join(unknown))
        return 2
    text = render()
    if "--check" in argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            sys.stderr.write("docs/VARIABLES_REFERENCE.md is out of date. Run: python scripts/gen_variable_reference.py\n")
            return 1
        print("docs/VARIABLES_REFERENCE.md is up to date")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote", os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
