#!/usr/bin/env python3
"""Write the fake ONTAP cluster for tests/netapp/run_netapp_test.sh (generic names only):

  fixture.py OUT.json [USER] [PASSWORD]

cluster1 with two nodes, one of them down, and one problem of every kind the report shows next to
healthy objects; times are relative to now (events in and out of the window, a certificate that
expires in 10 days, a node clock 400 s ahead). The fields each path allows are the ones checked
against NetApp's REST reference; the volumes path does not know snapshot_count and refuses
ignore_unknown_fields (like an older ONTAP), so the collector must fall back."""
import datetime
import json
import sys

now = datetime.datetime.now(datetime.timezone.utc)
iso = lambda d: (now + d).strftime("%Y-%m-%dT%H:%M:%S+00:00")
H, D = datetime.timedelta(hours=1), datetime.timedelta(days=1)
TB, GB = 1024 ** 4, 1024 ** 3


def vol(name, svm, aggr, size, used, state="online", vtype="rw", files=(1000, 100000), snap=(0, 5, 0), count=10):
    su, rp, sup = snap
    return {"name": name, "svm": {"name": svm}, "aggregates": [{"name": aggr}], "state": state, "type": vtype, "style": "flexvol",
            "space": {"size": size, "used": used, "available": size - used, "percent_used": round(100.0 * used / size),
                      "snapshot": {"used": su, "reserve_percent": rp, "reserve_size": size * rp // 100, "space_used_percent": sup}},
            "files": {"used": files[0], "maximum": files[1]}, "snapshot_count": count, "is_svm_root": False}


paths = {
    "/api/cluster": {"fields": ["name", "version.full", "uuid", "location", "timezone.name", "timezone"],
                     "single": {"name": "cluster1", "version": {"full": "NetApp Release 9.14.1P3: Mon Jan 01 2026"},
                                "uuid": "c1", "location": "lab", "timezone": {"name": "Etc/UTC"}}},
    "/api/cluster/nodes": {"fields": ["name", "state", "uptime", "date", "version.full", "model", "serial_number", "membership",
                                      "ha.enabled", "ha.partners.name", "ha.takeover.state", "ha.giveback.state", "controller.frus",
                                      "controller.failed_fan.count", "controller.failed_fan.message.message",
                                      "controller.failed_power_supply.count", "controller.failed_power_supply.message.message",
                                      "controller.over_temperature", "service_processor.state", "nvram.battery_state"],
                           "records": [
                               {"name": "cluster1-01", "state": "up", "uptime": 93784, "date": iso(datetime.timedelta(seconds=400)),
                                "version": {"full": "9.14.1P3"}, "model": "AFF-A400",
                                "ha": {"takeover": {"state": "not_attempted"}},
                                "controller": {"frus": [{"id": "PSU2", "type": "psu", "state": "error"}, {"id": "Fan1", "type": "fan", "state": "ok"}],
                                               "failed_fan": {"count": 0}, "failed_power_supply": {"count": 1, "message": {"message": "PSU2 failed"}},
                                               "over_temperature": "normal"},
                                "service_processor": {"state": "online"}, "nvram": {"battery_state": "battery_ok"}},
                               {"name": "cluster1-02", "state": "down", "uptime": 0, "model": "AFF-A400",
                                "controller": {"frus": [], "failed_fan": {"count": 0}, "failed_power_supply": {"count": 0}},
                                "service_processor": {"state": "offline"}, "nvram": {"battery_state": "battery_near_end_of_life"}}]},
    "/api/private/cli/system/health/subsystem": {"fields": ["subsystem", "health", "outstanding-alert-count"],
                                                 "records": [{"subsystem": "sas_connect", "health": "degraded", "outstanding_alert_count": 1},
                                                             {"subsystem": "environment", "health": "ok", "outstanding_alert_count": 0}]},
    "/api/private/cli/system/health/alert": {"fields": ["node", "monitor", "alert-id", "alerting-resource", "subsystem", "indication-time",
                                                        "perceived-severity", "probable-cause", "possible-effect", "corrective-actions"],
                                             "records": [{"node": "cluster1-01", "monitor": "node-connect", "alert_id": "DualPathToDiskShelf_Alert",
                                                          "alerting_resource": "shelf 1.1", "subsystem": "sas_connect",
                                                          "indication_time": iso(-2 * H), "perceived_severity": "major",
                                                          "probable_cause": "connection_establishment_error",
                                                          "corrective_actions": "Check the SAS cabling"}]},
    "/api/private/cli/storage/failover": {"fields": ["node", "partner-name", "possible", "state-description"],
                                          "records": [{"node": "cluster1-01", "partner_name": "cluster1-02", "possible": False,
                                                       "state_description": "Partner is down"}]},
    "/api/support/ems/events": {"fields": ["time", "message.name", "message.severity", "log_message", "node.name"],
                                "records": [{"time": iso(-1 * H), "message": {"name": "disk.failed", "severity": "alert"},
                                             "log_message": "Disk 1.0.3 failed", "node": {"name": "cluster1-01"}},
                                            {"time": iso(-2 * H), "message": {"name": "callhome.battery.low", "severity": "error"},
                                             "log_message": "NVRAM battery low", "node": {"name": "cluster1-02"}},
                                            {"time": iso(-3 * H), "message": {"name": "callhome.battery.low", "severity": "error"},
                                             "log_message": "NVRAM battery low (earlier)", "node": {"name": "cluster1-02"}},
                                            {"time": iso(-3 * D), "message": {"name": "old.event", "severity": "error"},
                                             "log_message": "outside the window", "node": {"name": "cluster1-01"}}]},
    "/api/storage/disks": {"fields": ["name", "state", "container_type", "node.name", "home_node.name", "model", "serial_number",
                                      "bay", "shelf.uid", "type", "class"],
                           "records": [{"name": "1.0.3", "state": "broken", "container_type": "broken", "node": {"name": "cluster1-01"},
                                        "home_node": {"name": "cluster1-01"}, "model": "X357", "serial_number": "S3", "bay": 3,
                                        "shelf": {"uid": "u1"}},
                                       {"name": "1.0.4", "state": "present", "container_type": "aggregate", "home_node": {"name": "cluster1-01"}},
                                       {"name": "1.0.5", "state": "present", "container_type": "aggregate", "home_node": {"name": "cluster1-02"}},
                                       {"name": "1.0.6", "state": "spare", "container_type": "spare", "home_node": {"name": "cluster1-02"}}]},
    "/api/storage/shelves": {"fields": ["name", "id", "uid", "model", "serial_number", "state", "frus", "fans", "temperature_sensors", "errors"],
                             "records": [{"name": "1.1", "id": "1", "uid": "u1", "model": "NS224", "state": "error",
                                          "frus": [{"type": "psu", "id": 1, "state": "ok"}, {"type": "psu", "id": 2, "state": "error"},
                                                   {"type": "module", "id": 0, "state": "ok"}],
                                          "fans": [{"id": 1, "state": "ok", "rpm": 3000}],
                                          "temperature_sensors": [{"id": 1, "state": "ok", "temperature": 31}],
                                          "errors": [{"reason": {"message": "Power supply 2 failed"}}]}]},
    "/api/storage/aggregates": {"fields": ["name", "node.name", "home_node.name", "state", "space.block_storage.size",
                                           "space.block_storage.available", "space.block_storage.used", "block_storage.primary.raid_type",
                                           "block_storage.primary.disk_count"],
                                "records": [{"name": "aggr1_n1", "node": {"name": "cluster1-01"}, "home_node": {"name": "cluster1-01"}, "state": "online",
                                             "space": {"block_storage": {"size": 10 * TB, "used": 9.2 * TB, "available": 0.8 * TB}},
                                             "block_storage": {"primary": {"raid_type": "raid_dp", "disk_count": 23}}},
                                            {"name": "aggr1_n2", "node": {"name": "cluster1-01"}, "home_node": {"name": "cluster1-02"}, "state": "online",
                                             "space": {"block_storage": {"size": 10 * TB, "used": 4 * TB, "available": 6 * TB}}}]},
    "/api/storage/volumes": {"fields": ["name", "svm.name", "aggregates.name", "state", "type", "style", "space.size", "space.available",
                                       "space.used", "space.percent_used", "space.snapshot.used", "space.snapshot.reserve_percent",
                                       "space.snapshot.reserve_size", "space.snapshot.space_used_percent", "files.maximum", "files.used",
                                       "is_svm_root"],
                             "supports_ignore": False,
                             "records": [vol("vol_full", "svm1", "aggr1_n1", 100 * GB, 95 * GB, snap=(20 * GB, 5, 400)),
                                         vol("vol_87", "svm1", "aggr1_n1", 100 * GB, 87 * GB),
                                         vol("vol_ok", "svm1", "aggr1_n2", 100 * GB, 40 * GB, files=(95000, 100000), snap=(3 * GB, 5, 60)),
                                         {"name": "vol_off", "svm": {"name": "svm1"}, "aggregates": [{"name": "aggr1_n2"}], "state": "offline",
                                          "type": "rw"},
                                         dict(vol("svm1_root", "svm1", "aggr1_n1", GB, GB - 1), is_svm_root=True)]},
    "/api/storage/luns": {"fields": ["name", "svm.name", "location.volume.name", "status.state", "status.mapped", "space.size", "space.used", "os_type"],
                          "records": [{"name": "/vol/vol_ok/lun_unmapped", "svm": {"name": "svm1"}, "location": {"volume": {"name": "vol_ok"}},
                                       "status": {"state": "online", "mapped": False}, "space": {"size": 10 * GB, "used": GB}, "os_type": "vmware"},
                                      {"name": "/vol/vol_ok/lun_off", "svm": {"name": "svm1"}, "status": {"state": "offline", "mapped": True},
                                       "space": {"size": GB, "used": 0}},
                                      {"name": "/vol/vol_ok/lun_good", "svm": {"name": "svm1"}, "status": {"state": "online", "mapped": True}}]},
    "/api/network/ip/interfaces": {"fields": ["name", "svm.name", "scope", "state", "enabled", "location.is_home", "location.home_node.name",
                                              "location.home_port.name", "location.node.name", "location.port.name", "ip.address", "services"],
                                   "records": [{"name": "lif_data1", "svm": {"name": "svm1"}, "state": "down", "enabled": True,
                                                "location": {"is_home": True, "home_node": {"name": "cluster1-02"}, "home_port": {"name": "e0c"},
                                                             "node": {"name": "cluster1-02"}, "port": {"name": "e0c"}},
                                                "ip": {"address": "10.0.0.11"}, "services": ["data_cifs"]},
                                               {"name": "lif_data2", "svm": {"name": "svm1"}, "state": "up", "enabled": True,
                                                "location": {"is_home": False, "home_node": {"name": "cluster1-02"}, "home_port": {"name": "e0d"},
                                                             "node": {"name": "cluster1-01"}, "port": {"name": "e0d"}}, "ip": {"address": "10.0.0.12"}},
                                               {"name": "lif_ok", "svm": {"name": "svm1"}, "state": "up", "enabled": True, "location": {"is_home": True}}]},
    "/api/network/fc/interfaces": {"fields": ["name", "svm.name", "state", "enabled", "location.is_home", "location.home_node.name",
                                              "location.home_port.name", "location.node.name", "location.port.name"], "records": []},
    "/api/network/ethernet/ports": {"fields": ["name", "node.name", "state", "enabled", "speed", "type", "broadcast_domain.name",
                                               "statistics.device.receive_raw.errors", "statistics.device.receive_raw.discards",
                                               "statistics.device.transmit_raw.errors", "statistics.device.link_down_count_raw"],
                                    "records": [{"name": "e0c", "node": {"name": "cluster1-01"}, "state": "down", "enabled": True, "type": "physical",
                                                 "broadcast_domain": {"name": "Default"}},
                                                {"name": "e0f", "node": {"name": "cluster1-01"}, "state": "down", "enabled": True, "type": "physical"},
                                                {"name": "e0a", "node": {"name": "cluster1-01"}, "state": "up", "enabled": True, "type": "physical",
                                                 "statistics": {"device": {"receive_raw": {"errors": 25, "discards": 2}, "transmit_raw": {"errors": 0},
                                                                           "link_down_count_raw": 3}}}]},
    "/api/cluster/counter/tables/nic_common/rows": {"fields": ["id", "properties", "counters"],
                                                    "records": [{"id": "cluster1-01:e0a",
                                                                 "properties": [{"name": "node.name", "value": "cluster1-01"}, {"name": "name", "value": "e0a"}],
                                                                 "counters": [{"name": "receive_crc_errors", "value": 12000}, {"name": "link_up_to_down", "value": 3}]}]},
    "/api/network/fc/ports": {"fields": ["name", "node.name", "state", "enabled", "physical_protocol", "speed.configured", "speed.maximum",
                                         "fabric.connected"],
                              "records": [{"name": "0e", "node": {"name": "cluster1-01"}, "state": "link_disconnected", "enabled": True},
                                          {"name": "0f", "node": {"name": "cluster1-01"}, "state": "link_not_connected", "enabled": True}]},
    "/api/private/cli/snapmirror": {"fields": ["source-path", "destination-path", "type", "state", "status", "healthy", "unhealthy-reason",
                                               "lag-time", "last-transfer-end-timestamp", "progress-last-updated", "total-progress",
                                               "last-transfer-error", "policy"],
                                    "records": [{"source_path": "src_svm:vol_a", "destination_path": "svm1:vol_a_dr", "state": "snapmirrored",
                                                 "status": "idle", "healthy": False, "unhealthy_reason": "Transfer failed.", "lag_time": "P3DT2H",
                                                 "last_transfer_end_timestamp": iso(-3 * D), "policy": "MirrorAllSnapshots"},
                                                {"source_path": "src_svm:vol_b", "destination_path": "svm1:vol_b_dr", "state": "snapmirrored",
                                                 "status": "transferring", "healthy": True, "lag_time": "PT1H5M", "total_progress": 5 * GB,
                                                 "progress_last_updated": iso(-0.01 * H), "policy": "MirrorAllSnapshots"},
                                                {"source_path": "src_svm:vol_c", "destination_path": "svm1:vol_c_dr", "state": "snapmirrored",
                                                 "status": "idle", "healthy": True, "lag_time": "PT30H", "policy": "MirrorAllSnapshots"},
                                                {"source_path": "src_svm:vol_d", "destination_path": "svm1:vol_d_dr", "state": "snapmirrored",
                                                 "status": "idle", "healthy": True, "lag_time": "PT2H", "policy": "MirrorAllSnapshots"}]},
    "/api/snapmirror/relationships": {"fields": ["source.path", "destination.path", "state", "healthy", "unhealthy_reason.message", "lag_time",
                                                 "transfer.state", "transfer.bytes_transferred", "transfer.end_time", "policy.name", "policy.type"],
                                      "records": []},
    "/api/cluster/peers": {"fields": ["name", "status.state", "authentication.state"],
                           "records": [{"name": "dr_cluster", "status": {"state": "unavailable"}, "authentication": {"state": "ok"}},
                                       {"name": "good_peer", "status": {"state": "available"}, "authentication": {"state": "ok"}}]},
    "/api/svm/peers": {"fields": ["svm.name", "peer.svm.name", "peer.cluster.name", "state"],
                       "records": [{"svm": {"name": "svm1"}, "peer": {"svm": {"name": "src_svm"}, "cluster": {"name": "dr_cluster"}}, "state": "peered"}]},
    "/api/svm/svms": {"fields": ["name", "state", "subtype"],
                      "records": [{"name": "svm1", "state": "running", "subtype": "default"},
                                  {"name": "svm_stopped", "state": "stopped", "subtype": "default"},
                                  {"name": "svm_dr", "state": "stopped", "subtype": "dp_destination"}]},
    "/api/protocols/cifs/services": {"fields": ["svm.name", "name", "enabled", "ad_domain.fqdn"],
                                     "records": [{"svm": {"name": "svm1"}, "name": "CIFS1", "enabled": True, "ad_domain": {"fqdn": "corp.example.mil"}},
                                                 {"svm": {"name": "svm2"}, "name": "CIFS2", "enabled": False, "ad_domain": {"fqdn": "corp.example.mil"}}]},
    "/api/protocols/cifs/domains": {"fields": ["svm.name", "discovered_servers"],
                                    "records": [{"svm": {"name": "svm1"}, "discovered_servers": [
                                        {"server_name": "dc1", "server_type": "ms_dc", "state": "ok"},
                                        {"server_name": "dc2", "server_type": "ms_dc", "state": "unavailable"}]}]},
    "/api/security/certificates": {"fields": ["name", "common_name", "svm.name", "type", "expiry_time", "scope"],
                                   "records": [{"name": "cluster1_server", "common_name": "cluster1.example.mil", "type": "server",
                                                "expiry_time": iso(10 * D), "scope": "cluster"},
                                               {"name": "far", "common_name": "far.example.mil", "type": "server", "expiry_time": iso(400 * D),
                                                "scope": "cluster"}]},
    "/api/cluster/ntp/servers": {"fields": ["server", "version", "authentication_enabled"], "records": [{"server": "ntp1.example.mil"}]},
}
user = sys.argv[2] if len(sys.argv) > 2 else "svc_ro"
password = sys.argv[3] if len(sys.argv) > 3 else "readonly-test"
with open(sys.argv[1], "w") as fh:
    json.dump({"user": user, "password": password, "paths": paths}, fh, indent=1)
